[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
# Base theme colors with red accent
primaryColor = "#dc2626"  # Bright red
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#fef2f2"  # Very light red
textColor = "#1f2937"  # Dark gray for better readability

[browser]
gatherUsageStats = false